### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by ckenst** [webdriverio/webdriverio-example-recipes#2]
Unfortunately a repo name of `recipes` isn't very descriptive. Perhaps `webdriverio-recipes` or something similar might be a little better naming convention.

**Comment by christian-bromann** [comment]
I was assuming that if the repository is within the webdriverio org people will know that these are wdio recipes.

**Comment by ckenst** [comment]
I did too. Then I cloned this repo and realized it wasn't very descriptive. So if you are like me and you have a bunch of repos on your machine, one generically called `recipes` isn't so helpful.

**Comment by christian-bromann** [comment]
You have a good point. I renamed the repo to `webdriverio-example-recipes`. Thanks!
